#!/bin/bash

MANIFEST=git://github.com/NezukoOS/manifest.git
BRANCH=eleven

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name Maitreya29
git config --global user.email maitreyapatni30@gmail.com

#sync
repo sync -c -j8 --force-sync --no-clone-bundle --no-tags

rm -rf packages/apps/Settings
git clone --depth=1 https://"$auth"@github.com/NezukoOS/Sextings packages/apps/Settings
git clone --depth=1 git@github.com:NezukoOS/packages_apps_Settings_DescendantHealth.git packages/apps/Settings/DescendantHealth
git clone --depth=1 https://github.com/Maitreya29/android_device_oneplus_msm8998-common device/oneplus/msm8998-common

git clone --depth=1 https://github.com/Maitreya29/android_device_oneplus_dumpling device/oneplus/dumpling

git clone --depth=1 https://"$auth"@github.com/Maitreya29/vendor_oneplus vendor/oneplus

git clone --depth=1 https://github.com/ederekun/lazy_kernel_op5-t kernel/oneplus/msm8998

git clone --depth=1 https://github.com/kdrag0n/proton-clang prebuilts/clang/host/linux-x86/clang-proton
