#!/bin/bash

MANIFEST=git://github.com/NezukoOS/manifest.git
BRANCH=eleven

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name Maitreya29
git config --global user.email maitreyapatni30@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

rm -rf packages/apps/Settings
git clone https://$auth@github.com/NezukoOS/Sextings packages/apps/Settings

git clone https://github.com/Maitreya29/android_device_oneplus_msm8998-common device/oneplus/msm8998-common

git clone https://github.com/Maitreya29/android_device_oneplus_dumpling device/oneplus/dumpling

git clone https://$auth@github.com/sibinsilva/android_vendor_oneplus vendor/oneplus

git clone --depth=1 https://github.com/ederekun/lazy_kernel_op5-t kernel/oneplus/msm8998

git clone --depth=1 https://github.com/kdrag0n/proton-clang prebuilts/clang/host/linux-x86/clang-proton
